### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by MichalLauer** [nvbach91/4IZ268-2022-2023-ZS#149]
Dobrý den,

v semestrální práci chci použít Twitter API, ale až nyní jsem zjitil, že ji lze spustit pouze na backendu. Bylo by možné místo API použít web scraping a získat výsledky z vyhledávání?

Děkuji předem,
Lauer

**Comment by nvbach91** [comment]
@MichalLauer vytvořil jsem tzv. proxy, můžete ho případně využít https://github.com/nvbach91/cors-proxy
