### ISSUE TITLE
permission denied to repository

### ISSUE THREAD

**Issue by psaniac** [nvbach91/4IZ268-2022-2023-ZS#150]
Dobrý den, pří spuštění příkazu 
git push --set-upstream origin student-staj20
podle návodu
https://github.com/nvbach91/4IZ268-2022-2023-ZS/wiki/Postup-odevdani-SP-pres-Git
mi to dává chybu
remote: Permission to nvbach91/4IZ268-2022-2023-ZS.git denied to psaniac.
fatal: unable to access 'https://github.com/nvbach91/4IZ268-2022-2023-ZS.git/': The requested URL returned error: 403

Asi nějak se vám podařilo mě odebrat z uživatelů, kteří mají právo nahrávat soubory na tento repozitář.
Prosím opravte to.
Prozatím je moje práce SP2 tady: https://github.com/psaniac/sp2

**Comment by nvbach91** [comment]
Poslal jsem Vám invite do repo, můžete si založit PR. Jinak díval jsem se na aplikaci, ale není použitelná (nelze se dostat do odpovídání na text) a zamýšlený způsob fungování aplikace není akceptovatelný - je potřeba ji naimplementovat jako single-page.

![image](https://user-images.githubusercontent.com/20724910/210860594-8895c64f-e711-44db-be79-b149ceb87cd9.png)
