### ISSUE TITLE
vlct01-sp1

### ISSUE THREAD

**Issue by tomas-vlcek** [nvbach91/4IZ268-2022-2023-ZS#155]
Dobrý den, 

níže je k dispozici opravená verze mé první semestrální práce.

Původní verze webových stránek dostupná [zde](https://esotemp.vse.cz/~vlct01/sp1/).
Opravená (nová) verze webových stránek dostupná [zde](https://esotemp.vse.cz/~vlct01/sp1.1/).

V nové verzi jsou upraveny všechny připomínky zmíněné v [tomto commitu](https://github.com/nvbach91/4IZ268-2022-2023-ZS/commit/042531d10f95bd574096220ee10eee8f6a924801#diff-68b9ada6d0af250bb98159f52af1223e3dcb6e6bd5e1fd71da52df23521c3ec0).

Konkrétně pak problémy.
1. vyraznejsim zpusobem odlisit aktivni polozky navigace (barvou na pozadi) + zvetsit klikatelny prostor
2. chybi import fontu, font naimportujte pres HTML tag <link>
3. kdyz jsem v about a kliknu na navigaci about, tak dostavam Not found

Předem děkuji za opětovné zhodnocení.

**Comment by nvbach91** [comment]
Super
