### ISSUE TITLE
zadání sp2 sout03

### ISSUE THREAD

**Issue by TeaJunkie1** [nvbach91/4IZ268-2022-2023-ZS#178]
dobrý den,

chtěl bych si okontrolovat, zda li můj progress na SP2 je v souladu se zadáním práce, ale bohužel nemohu najít email od google forms se zadáním, nemohl byste mi prosím přeposlat zadání na školní mail sout03@vse.cz?

Moc děkuju

TS

**Comment by nvbach91** [comment]
<html>
<body>
<google-sheets-html-origin>

12/18/2022 19:03:23 | Generátor přání (christmas cards, get well cards atd.) uživatel si buď načte svůj obrázek, nebo si nechá ho nechá navrhnout (pexels API), do obrázku si napíše svoje přání a následně si ho buď může stáhnout na svůj disk a nebo ho může postnout na sociální síť (Facebook, twitter, instagram) | aplikace bude umět načtení obrázku, případně nabídnout uživateli obrázek po specifikaci tématu přání, umožnit uživateli psát na obrázek svůj text (+ výběr fontu z několika možných a výběr barvy textu, výběr velikosti textu) + možnost sdílet vytvořené přání na sociálních sítí, nebo si stáhnout přání lokálně. | https://www.pexels.com/api/documentation/ -> pro načítání obrázků, ze kterých si uživatel vytvoří přáníhttps://developer.twitter.com/en/docs/twitter-api -> uživatel si může postnout přání na svoji zeďhttps://developers.facebook.com/docs/instagram-api/ -> uživatel si může postnout přání na svoji zeďhttps://developers.facebook.com/docs/graph-api/  -> -> uživatel si může postnout přání na svoji zeď | https://html2canvas.hertzen.com/documentation -> pro vytvoření screenshotu, který se uloží na lokál uživatelehttps://jquery.com/ -> pro jednodušší práci https://axios-http.com/docs/intro -> pro jednodušší práci s APIčky (AJAX) | https://drive.google.com/open?id=1Wd_DJGpbOeTVCDjNBnpoKSwLZWLWPJvV
-- | -- | -- | -- | -- | --



</body>
</html>

**Comment by nvbach91** [comment]
@TeaJunkie1
