### ISSUE TITLE
mikm25-sp1

### ISSUE THREAD

**Issue by marek-mikula** [nvbach91/4IZ268-2022-2023-ZS#19]
Vlákno pro trackování stavu schválení/neschválení návrhu mé SP1, abych se co nejdříve mohl pustit do práce

**Comment by marek-mikula** [comment]
@nvbach91 Dobrý den, jaký je status mého návrhu?

**Comment by nvbach91** [comment]
Navrh SP1 je ok

**Comment by marek-mikula** [comment]
Paráda, děkuji! <3
