### ISSUE TITLE
mikm25-sp2

### ISSUE THREAD

**Issue by marek-mikula** [nvbach91/4IZ268-2022-2023-ZS#20]
Vlákno pro trackování stavu schválení/neschválení návrhu mé SP2, abych se co nejdříve mohl pustit do práce

**Comment by marek-mikula** [comment]
@nvbach91 Dobrý den, jaký je status mého návrhu?

**Comment by nvbach91** [comment]
Musite jeste pridat do projektu nejakou funkci AJAX

**Comment by marek-mikula** [comment]
@nvbach91

V tom případě bych trochu změnil zadání.

Napadla mě aplikace, kde bych uživatele nechal vybrat nějakou měnu (CZK, EUR, USD), následně by uživatel vybral nějakou kryptoměnu (BTC, ETH, LTC, možná i nějaké další). Po vybrání obou měn bych mu zobrazil graf vývoje ceny dané kryptoměny ku běžné fiat měně, kterou vybral.

Našel jsem jednu společnost, které takové API poskytuje. V základním balíčku bych měl mít k dispozici 100 requestů / den, což asi zvládnu.

https://www.coinapi.io/

Jelikož se jedná spíš o semestrální práci věnovanou JS, mohl bych použít pro design Bootstrap?

Pro vykreslení grafu bych použil např. knihovnu Highcharts nebo nějakou jí podobnou.

Návrh:
![navrh2](https://user-images.githubusercontent.com/46525863/198582582-2ac86a61-e620-4a58-a3c8-24e852b7414f.png)

**Comment by nvbach91** [comment]
Ok, a v SP2 muzete pouzit uplne vsechno

**Comment by marek-mikula** [comment]
@nvbach91 Děkuji za bleskurychlou reakci, pustím se do práce.
